#!/usr/bin/zsh

# Opções...
editor="nano"

# Varuaeis

data=$( date +'%d/%m/%Y' )

header="#!/usr/bin/zsh
#-----------------------------------------------------
# Script   : $(basename $1)
# Descrição:
# Versão   : 0.1
# Autor    : $USER
# Data     : $data
# Licença  : GNU/GLP v3.0
#-----------------------------------------------------
# Uso:
#-----------------------------------------------------
"

# Testar se usuário passou o número certo de argumentos (1)
[[ $# -ne 1 ]] && echo "É aceito apenas *um* nome de arquivo!" && exit 1

# Testar se arquivo já existe
[[ -f $1 ]] && echo "Arquivo já existe!" && exit 1

echo "$header" > $1
chmod +x $1
$editor $1

exit 0
